### ISSUE TITLE
NCCL Timeout During LoRA Training

### ISSUE THREAD

**Issue by kl844477** [NVIDIA-NeMo/Megatron-Bridge#1376]
Training hangs and times out after 10 minutes during the first forward pass with NCCL collective operation timeout in LoRA adapter's tensor parallel all-gather operation.

## Environment
- Model: Qwen3-Coder-480B-A35B-Instruct (MoE model)
- Configuration:
Tensor Parallel: 8
Pipeline Parallel: 1
Expert Model Parallel: 8
Expert Tensor Parallel: 1
Micro batch size: 1

## Error
```bash
torch.distributed.DistBackendError: [Rank X] Watchdog caught collective operation timeout: 
WorkNCCL(SeqNum=7, OpType=_ALLGATHER_BASE, NumelIn=XXXX, NumelOut=XXXX, Timeout(ms)=600000) 
ran for 600000 milliseconds before timing out.
```

Might be related to #1363

**Comment by HollowMan6** [comment]
Hi @kl844477 , I think I just fixed this via #1380, would you mind using that PR to check if your problem also gets resolved?

**Comment by kl844477** [comment]
Hi @HollowMan6, I can confirm that the merged PR solves the problem. Sry for my late reply, I couldn't test this earlier and thanks for addressing this

**Comment by pruprakash** [comment]
## QA RCCA Analysis

### 1. Fix Reference
- **PR**: #1380 - [PEFT/LoRA] fix: using ETP instead of TP for expert layers
- **Issue**: #1376 - NCCL Timeout During LoRA Training

### 2. Root Cause
Training hung and timed out during the first forward pass with NCCL collective operation timeout in LoRA adapter's tensor parallel all-gather operation. LoRA was incorrectly using TP (Tensor Parallel) instead of ETP (Expert Tensor Parallel) for expert layers in MoE models.

**Fix**: Use ETP instead of TP for expert layers in LoRA adapters.

### 3. Trigger Configuration
- Qwen3-Coder-480B-A35B-Instruct (MoE model)
- LoRA training with TP=8, EP=8
- NCCL timeout during first forward pass

### 4. Nature of the Bug
**Classification**: CODE BUG - Wrong parallelism for expert layers in LoRA

### 5. Existing Test Coverage
**In Fix PR #1380**: YES - unit tests added
- `tests/unit_tests/peft/test_canonical_lora.py`
- `tests/unit_tests/peft/test_utils.py`

### 6. Coverage Assessment
| Test Type | Exists | Covers Bug |
|-----------|--------|------------|
| Unit test for LoRA expert layers | YES (PR) | YES |

### 7. Conclusion
**Verdict**: ADEQUATE COVERAGE

Fix PR #1380 includes unit tests for LoRA expert layer parallelism.
