### ISSUE TITLE
Training hangs indefinitely at first validation

### ISSUE THREAD

**Issue by kl844477** [NVIDIA-NeMo/Megatron-Bridge#1477]
## Description
Training with Qwen3-480B MoE runs successfully for k training iterations but hangs indefinitely when attempting the first validation step. No error is thrown, and the process appears to freeze without making progress.

### Hang Occurs
After iteration k, when validation is triggered, the process hangs with no further output. Multiple InfiniBand async event warnings appear starting when starting validation:

```bash
host1:55690:56357 [0] ibvwrap.c:102 NCCL WARN Call to ibv_get_async_event failed
host1:55688:56358 [0] ibvwrap.c:102 NCCL WARN Call to ibv_get_async_event failed
host1:55689:56356 [0] ibvwrap.c:102 NCCL WARN Call to ibv_get_async_event failed
host1:55691:56359 [0] ibvwrap.c:102 NCCL WARN Call to ibv_get_async_event failed
[... multiple similar warnings across all GPUs ...]
```

I'm using commit ce111f9bf2d89044d49f57853b4e6bcdca135e5b

See [full configuration](https://gist.github.com/kl844477/461718b8db7d975bda2b7f2b51bd447c)

Any help/feedback is highly appreciated

**Comment by yaoyu-33** [comment]
@kl844477  Can you share your env, and command you are using. Are you seeing it with smaller model like qwen3 moe 30ba3b as well?

**Comment by kl844477** [comment]
Hey, I also see the same problem when training a Qwen3 30B-A3B model. I use the nemo:25.03 image. Our nodes run with driver R570.

This is the launch script, which is executed on each node:
```bash
#!/bin/bash 

NNODES=2
NUM_GPUS=8
MASTER_ADDR=<addr>
MASTER_PORT=29501

# ============================================
# NCCL INFINIBAND CONFIGURATION
# ============================================

export NCCL_IB_DISABLE=0
export NCCL_IB_HCA=mlx5_4,mlx5_7,mlx5_8,mlx5_9,mlx5_11,mlx5_13,mlx5_14,mlx5_15
export NCCL_IB_GID_INDEX=3
export NCCL_IB_TC=106
export NCCL_IB_TIMEOUT=120
export NCCL_NET_GDR_LEVEL=5
export NCCL_NET_GDR_READ=1
export NCCL_NSOCKS_PERTHREAD=4
export NCCL_SOCKET_NTHREADS=2
export NCCL_IB_QPS_PER_CONNECTION=4
export NCCL_SOCKET_IFNAME=bond0
# export NCCL_DEBUG=INFO
export NCCL_DEBUG=WARN


export CUDA_DEVICE_MAX_CONNECTIONS=1

export TORCH_ALLOW_TF32_CUBLAS_OVERRIDE=1
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

LOG_FILE="logs/training_$(date +%Y-%m-%d_%H:%M:%s).log"

torchrun \
    --nnodes=${NNODES} \
    --nproc-per-node=${NUM_GPUS} \
    --rdzv_backend=c10d \
    --rdzv_endpoint=${MASTER_ADDR}:${MASTER_PORT} \
    --rdzv_id=9487 \
        finetune_Qwen3.py \
        2>&1 | tee $LOG_FILE
```

and this is the corresponding python script which for the Qwen3-30B model:
```python
#!/usr/bin/env python3
import argparse
import logging
import os
import sys
from pathlib import Path
from typing import Tuple

from omegaconf import OmegaConf

import torch
from megatron.core.distributed import DistributedDataParallelConfig
from typing_extensions import TypedDict, Unpack

from megatron.bridge import AutoBridge
from megatron.bridge.peft.base import PEFT
from megatron.bridge.recipes.utils.dataset_utils import get_blend_fields_from_data_paths
from megatron.bridge.recipes.utils.finetune_utils import default_peft_config, default_squad_config
from megatron.bridge.recipes.utils.optimizer_utils import distributed_fused_adam_with_cosine_annealing
from megatron.bridge.recipes.utils.tokenizer_utils import DEFAULT_NULL_TOKENIZER_VOCAB_SIZE
from megatron.bridge.training.comm_overlap import CommOverlapConfig
from megatron.bridge.training.config import (
    CheckpointConfig,
    ConfigContainer,
    GPTDatasetConfig,
    LoggerConfig,
    RNGConfig,
    TokenizerConfig,
    TrainingConfig,
    FinetuningDatasetConfig,
)
from megatron.bridge.training.mixed_precision import MixedPrecisionConfig
from megatron.bridge.recipes.qwen_vl import qwen25_vl as qwen_vl_recipes
from megatron.bridge.recipes.qwen import qwen3
from megatron.bridge.training.pretrain import pretrain
from megatron.bridge.training.utils.omegaconf_utils import (
    apply_overrides,
    create_omegaconf_dict_config,
    parse_hydra_overrides,
)
from megatron.bridge.peft.lora import LoRA
from megatron.bridge.training.gpt_step import forward_step
from megatron.bridge.utils.common_utils import get_rank_safe
from megatron.bridge.data.datasets.packed_sequence import PackedSequenceSpecs


logger: logging.Logger = logging.getLogger(__name__)


SCRIPT_DIR: Path = Path(__file__).parent.resolve()
DEFAULT_CONFIG_FILENAME: str = "qwen25_vl_pretrain_override_example.yaml"
DEFAULT_CONFIG_FILE_PATH: Path = SCRIPT_DIR / "conf" / DEFAULT_CONFIG_FILENAME





def main() -> None:
    hf_path=<PATH_TO_QWEN3_MOE>
    MEGATRON_PRETRAINED_CHECKPOINT = <PATH_TO_MEGATRON_CHECKPOINT>

    tp=4
    pp=2
    cp=1
    seqp=True
    emp=4
    etp=1

    account_for_embedding_in_pipeline_split = True
    account_for_loss_in_pipeline_split = True

    use_megatron_fsdp: bool = False
    use_null_tokenizer: bool = False
    enable_recompute: bool = False
    train_iters: int = 10000
    global_batch_size: int = 128
    micro_batch_size: int = 1
    seq_length: int = 10000
    lr: float = 1e-4
    min_lr: float = 3e-5
    lr_warmup_iters: int = 50
    lr_decay_iters: int = 100
    eval_interval: int = 50
    save_interval: int = 100
    # Precision recipe
    precision_config: MixedPrecisionConfig | str | None = "bf16_mixed"
    # precision_config: MixedPrecisionConfig | str | None = "bf16_with_mxfp8_mixed"
    # precision_config: MixedPrecisionConfig | str | None = "bf16_with_fp8_current_scaling_mixed"
    # precision_config: MixedPrecisionConfig = precision
    comm_overlap_config: CommOverlapConfig | None = None
    packed_sequence: bool = False

    name="megaton_bridge_test"
    base_output_dir = os.path.join(os.getcwd(), "nemo_experiments")
    run_output_dir = os.path.join(base_output_dir, name)
    checkpoint_dir = os.path.join(run_output_dir, "checkpoints")
    tensorboard_dir = os.path.join(run_output_dir, "tb_logs")


    bridge = AutoBridge.from_hf_pretrained(hf_path)
    model_cfg = bridge.to_megatron_provider(load_weights=False)
    model_cfg.tensor_model_parallel_size = tp
    model_cfg.pipeline_model_parallel_size = pp
    model_cfg.pipeline_dtype = torch.dtype
    model_cfg.virtual_pipeline_model_parallel_size = None
    model_cfg.context_parallel_size = cp
    model_cfg.calculate_per_token_loss = cp > 1 
    model_cfg.sequence_parallel = seqp
    model_cfg.seq_length = seq_length
    model_cfg.expert_model_parallel_size = emp
    model_cfg.expert_tensor_parallel_size = etp

    if account_for_embedding_in_pipeline_split:
        model_cfg.account_for_embedding_in_pipeline_split = True
    if account_for_loss_in_pipeline_split:
        model_cfg.account_for_loss_in_pipeline_split = True

    if enable_recompute:
        model_cfg.recompute_granularity = "full"
        model_cfg.recompute_method = "uniform"
        model_cfg.recompute_num_layers = 1

    opt_cfg, scheduler_cfg = distributed_fused_adam_with_cosine_annealing(
        lr_warmup_iters=lr_warmup_iters,
        lr_decay_iters=lr_decay_iters,
        max_lr=lr,
        min_lr=min_lr,
    )

    # Config Container
    cfg_container = ConfigContainer(
        model=model_cfg,
        train=TrainingConfig(
            train_iters=train_iters,
            eval_interval=eval_interval,
            eval_iters=32,
            global_batch_size=global_batch_size,
            micro_batch_size=micro_batch_size,
            manual_gc=True,
            manual_gc_interval=100,
            manual_gc_eval=100,
        ),
        optimizer=opt_cfg,
        scheduler=scheduler_cfg,
        ddp=DistributedDataParallelConfig(
            check_for_nan_in_grad=True,
            grad_reduce_in_fp32=True,
            overlap_grad_reduce=True,
            overlap_param_gather=True,
            average_in_collective=False if cp > 1 else True,  # Not supported for custom FSDP for now, need to be set to False if using FSDP
            data_parallel_sharding_strategy="optim_grads_params",  # For custom FSDP only
            use_distributed_optimizer=True,
            use_megatron_fsdp=use_megatron_fsdp,  # need use_distributed_optimizer=True
        ),
        
        dataset=FinetuningDatasetConfig(
            dataset_root=<DATA_ROOT>,
            seq_length=seq_length,
            packed_sequence_specs=PackedSequenceSpecs(
                packed_sequence_size=seq_length,
                tokenizer_model_name="Qwen3",
                ),
        ),
        logger=LoggerConfig(
            log_interval=10,
            tensorboard_dir=tensorboard_dir,
            log_timers_to_tensorboard=True,
        ),
        tokenizer=TokenizerConfig(
            tokenizer_type="NullTokenizer" if use_null_tokenizer else "HuggingFaceTokenizer",
            tokenizer_model=hf_path if not use_null_tokenizer else None,
            vocab_size=DEFAULT_NULL_TOKENIZER_VOCAB_SIZE if use_null_tokenizer else None,
        ),
        checkpoint=CheckpointConfig(
            pretrained_checkpoint=MEGATRON_PRETRAINED_CHECKPOINT,
            save_interval=save_interval,
            save=checkpoint_dir,

            ckpt_format="torch_dist",
            fully_parallel_save=True,
        ),
        peft=LoRA(
            target_modules=["linear_qkv", "linear_proj", "linear_fc1", "linear_fc2"],    
            dim=16,
            alpha=32,
            dropout=0.1,
        ),
        rng=RNGConfig(seed=1234),
        comm_overlap=comm_overlap_config,
        mixed_precision=precision_config,
    )
    
    pretrain(config=cfg_container, forward_step_func=forward_step)


if __name__ == "__main__":
    main()
```

**Comment by kl844477** [comment]
Hey, I'm really sorry about this issue. The problem was on my side. For validation, I only used a small portion of my data, which lead to not enough samples when increasing the sequence length of the packed sequence dataset. Validation hangs because the ranks with no samples are blocking. It might be worth adding a check.

**Comment by snowmanwwg** [comment]
@kl844477 want to check in - do you still need help? thank you!

**Comment by kl844477** [comment]
@snowmanwwg It's working, I close the issue and reopen if needed. Thanks for your help.

**Comment by pruprakash** [comment]
## QA RCCA Coverage Analysis

### 1. Issue Summary
Training with Qwen3-480B MoE hangs indefinitely during the first validation step. No error was thrown and NCCL/InfiniBand warnings appeared.

### 2. Root Cause
**USER ERROR** - The user explained:
> "The problem was on my side. For validation, I only used a small portion of my data, which lead to not enough samples when increasing the sequence length of the packed sequence dataset. Validation hangs because the ranks with no samples are blocking."

### 3. Fix Analysis
**No fix was required** - This was a configuration issue on the user's side. The user had insufficient validation data which caused some ranks to have no samples, leading to a blocking condition.

### 4. Verdict
**NOT A BUG - USER ERROR**

The issue was caused by user configuration (insufficient validation data for packed sequences with increased sequence length).

### 5. Recommendations
The user suggested:
> "It might be worth adding a check."

Consider adding validation to detect and warn when some ranks have no data samples to prevent silent hangs.
