### ISSUE TITLE
[BUG] Infinite CUDA OOM during HF export with Activation Recomputation enabled (DeepSeekV3 / MoE)

### ISSUE THREAD

**Issue by LucaTedeschini** [NVIDIA-NeMo/Megatron-Bridge#1855]
**Describe the bug**
When exporting a Megatron checkpoint trained with Activation Recomputation enabled, the HuggingFace export enters an infinite CUDA OOM loop during tensor merging.

I'm training a model using the `DeepSeekV3Provider`. The important configurations are:

```python
# offloading parameters
recompute_granularity = 'full'
recompute_method = "uniform"
recompute_num_layers = 2

# Parallelism configs
tensor_model_parallel_size = 1
pipeline_model_parallel_size = 1
expert_model_parallel_size = 8
context_parallel_size = 1

# Precision
mixed_precision = "bf16_with_fp8_current_scaling_mixed"
```

Recomputation is required because the full model cannot be loaded on a single GPU without exceeding available VRAM.
The model has around 14B parameters. With these configurations, the training works fine. Once it was trained, I tried to convert it to HF format using the script [provided by bridge](https://github.com/NVIDIA-NeMo/Megatron-Bridge/blob/main/examples/conversion/convert_checkpoints.py), resulting in the following output:

```log
(.venv_b) ltedeschini@workstation:~/workspace$ python3 convert_bridge_example.py export --hf-model deepseek-ai/DeepSeek-V3 --megatron-path path/to/checkpoint --hf-path ./export
🔄 Starting export: path/to/checkpoint -> ./export
📂 Found Megatron checkpoint: path/to/checkpoint 
📋 Found configuration: path/to/checkpoint /run_config.yaml
📤 Exporting to HuggingFace format...
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[...]
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
Broadcasting config from rank 0 to all 1 ranks
 > number of parameters on (tensor, pipeline) model parallel rank (0, 0): 14092190208
sharded_state_dict metadata loaded from the checkpoint: {'singleton_local_shards': False, 'distrib_optim_sharding_type': 'dp_reshardable', 'chained_optim_avoid_prefix': True}
make_tp_sharded_tensor_for_checkpoint received extra kwargs: ['allow_shape_mismatch']
/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/core/dist_checkpointing/strategies/torch.py:956: FutureWarning: `load_state_dict` is deprecated and will be removed in future versions. Please use `load` instead.
  checkpoint.load_state_dict(
/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/torch/distributed/checkpoint/planner_helpers.py:418: FutureWarning: Please use DTensor instead and we are deprecating ShardedTensor.
  device = getattr(value, "device", None)
/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/torch/distributed/checkpoint/default_planner.py:479: FutureWarning: Please use DTensor instead and we are deprecating ShardedTensor.
  and md.size != obj.size()
CUDA OutOfMemoryError encountered during tensors merging. Switching to CPU merge. (Error: CUDA out of memory. Tried to allocate 10.00 MiB. GPU 0 has a total capacity of 79.18 GiB of which 6.56 MiB is free. Including non-PyTorch memory, this process has 55.66 GiB memory in use. Of the allocated memory 54.90 GiB is allocated by PyTorch, and 97.46 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables))
CUDA OutOfMemoryError encountered during tensors merging. Switching to CPU merge. (Error: CUDA out of memory. Tried to allocate 10.00 MiB. GPU 0 has a total capacity of 79.18 GiB of which 6.56 MiB is free. Including non-PyTorch memory, this process has 55.66 GiB memory in use. Of the allocated memory 54.90 GiB is allocated by PyTorch, and 97.46 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables))
[...]
```

and the OOM error repeats indefinitely.

**Steps/Code to reproduce bug**

Unfortunately I cannot provide a minimal repro since I think it is related to hardware requirements, but the issue consistently reproduces with the configuration below on 8×H100.

```python
model_provider_moe = DeepSeekV3ModelProvider(
        num_layers=26,
        hidden_size=2048,
        ffn_hidden_size=1280,
        seq_length=4096,
        vocab_size=128256,
        num_moe_experts = 64,
        moe_ffn_hidden_size = 1280,
        moe_shared_expert_intermediate_size = 1280 * 1,
        moe_layer_freq = [1] * 26, 
        moe_router_topk = 2,

        
        moe_router_num_groups = 8,
        moe_router_group_topk = 2,
        moe_router_score_function = "sigmoid",
        moe_router_enable_expert_bias =True,
        moe_aux_loss_coeff = 1e-4,
        moe_router_topk_scaling_factor = 2.5,
        make_vocab_size_divisible_by = 1280,
        moe_router_bias_update_rate = 1e-3,

        tensor_model_parallel_size = 1,
        pipeline_model_parallel_size = 1,
        expert_model_parallel_size = 8,
        sequence_parallel = False,
        context_parallel_size = 1,
        moe_permute_fusion=False,
        moe_grouped_gemm = True,

        num_attention_heads = 16,
        num_query_groups = 4,
        multi_latent_attention = False,
        recompute_granularity =  'full',
        recompute_method = 'uniform',
        recompute_num_layers = 2
    )
```

with `precision = "bf16_with_fp8_current_scaling_mixed"`. The training works fine but when converting, the issue appears.

**Expected behavior**

The model should be exported successfully.

**Additional context**

I tried to investigate the problem slightly, and what seems strange to me is that in the `export_ckpt` method:

https://github.com/NVIDIA-NeMo/Megatron-Bridge/blob/d94cb20e4108b1ea3b8dc80f55e8f487bfc2cce0/src/megatron/bridge/models/conversion/auto_bridge.py#L702-L710

called by the script, the conversion procedure should be performed in a temporary CPU distributed environment, not on the GPU.

Additionally, I think this problem is related to the fact that when I try to resume training with the flag `load_optim=True`, the training does not start, and it goes OOM. If I set the flag to `False`, the training starts successfully.
This is probably related is some way to Activation Recomputation, but I don't understand how since it should work on activations and not the optimizer state, if I'm not mistaken. Regarding this issue, I think that the conversion script loads the optimizer in GPU memory, resulting in OOM.

I tried to export a smaller model checkpoint that can be loaded on a single GPU **without recomputation**, and the procedure worked fine.

I think this issue is similar to https://github.com/NVIDIA-NeMo/Megatron-Bridge/issues/1748. My bridge version is:

```python
>>> import megatron.bridge as bridge
>>> import torch
>>> bridge.__version__
'0.3.0rc0'
>>> torch.__version__
'2.9.1+cu128'
```

I tried forcing the conversion on CPU by setting the cuda visible devices to `""`, with this result

```log
(.venv_b) ltedeschini@workspace:~/workspace$ CUDA_VISIBLE_DEVICES="" python3 convert_bridge_example.py export --hf-model deepseek-ai/DeepSeek-V3 --megatron-path path/to/checkpoint --hf-path ./export
W0105 10:36:41.077000 3175610 .venv_b/lib/python3.12/site-packages/torch/utils/cpp_extension.py:117] No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-12.8'
/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/fla/utils.py:354: UserWarning: Triton is not supported on current platform, roll back to CPU.
  warnings.warn(('Triton is not supported on current platform, roll back to CPU.'), stacklevel=1)
🔄 Starting export: bridge_experiments/model_A_fp8_offloading2_mbs4_tp1_pretrain_3/checkpoints/iter_0041954/ -> ./AAA_test_export
📂 Found Megatron checkpoint: bridge_experiments/model_A_fp8_offloading2_mbs4_tp1_pretrain_3/checkpoints/iter_0041954
📋 Found configuration: bridge_experiments/model_A_fp8_offloading2_mbs4_tp1_pretrain_3/checkpoints/iter_0041954/run_config.yaml
📤 Exporting to HuggingFace format...
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[...]
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
Broadcasting config from rank 0 to all 1 ranks
[rank0]: Traceback (most recent call last):
[rank0]:   File "/media/storage/store1/ltedeschini/convert_bridge_example.py", line 273, in <module>
[rank0]:     sys.exit(main())
[rank0]:              ^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/convert_bridge_example.py", line 257, in main
[rank0]:     export_megatron_to_hf(
[rank0]:   File "/media/storage/store1/ltedeschini/convert_bridge_example.py", line 183, in export_megatron_to_hf
[rank0]:     bridge.export_ckpt(
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/bridge/models/conversion/auto_bridge.py", line 705, in export_ckpt
[rank0]:     megatron_model = self.load_megatron_model(megatron_path, wrap_with_ddp=False)
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/bridge/models/conversion/auto_bridge.py", line 595, in load_megatron_model
[rank0]:     model = load_megatron_model(
[rank0]:             ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/bridge/training/model_load_save.py", line 388, in load_megatron_model
[rank0]:     return build_and_load_model(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/bridge/training/model_load_save.py", line 328, in build_and_load_model
[rank0]:     return _load_checkpoint()
[rank0]:            ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/bridge/training/model_load_save.py", line 306, in _load_checkpoint
[rank0]:     model = _call_model_provider(model_cfg)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/bridge/training/model_load_save.py", line 274, in _call_model_provider
[rank0]:     return model_cfg.provide_distributed_model(wrap_with_ddp=False, use_cpu_initialization=use_cpu_init)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/bridge/models/model_provider.py", line 179, in provide_distributed_model
[rank0]:     model = get_model(
[rank0]:             ^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/bridge/models/model_provider.py", line 526, in get_model
[rank0]:     model = _create_model(model_provider, model_type)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/bridge/models/model_provider.py", line 632, in _create_model
[rank0]:     model = model_provider.provide(
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/bridge/models/gpt_provider.py", line 254, in provide
[rank0]:     model = MCoreGPTModel(
[rank0]:             ^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/core/models/gpt/gpt_model.py", line 205, in __init__
[rank0]:     self.decoder = TransformerBlock(
[rank0]:                    ^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/core/transformer/transformer_block.py", line 308, in __init__
[rank0]:     get_cpu_offload_context(
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/megatron/core/extensions/transformer_engine.py", line 2003, in get_cpu_offload_context
[rank0]:     context, sync_func = _get_cpu_offload_context(
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/transformer_engine/pytorch/cpu_offload.py", line 723, in get_cpu_offload_context
[rank0]:     cpu_offload_handler = AsyncDoubleBufferGroupOffloadHandler(
[rank0]:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/transformer_engine/pytorch/cpu_offload.py", line 353, in __init__
[rank0]:     self.d2h_stream = torch.cuda.Stream()
[rank0]:                       ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/media/storage/store1/ltedeschini/.venv_b/lib/python3.12/site-packages/torch/cuda/streams.py", line 37, in __new__
[rank0]:     return super().__new__(cls, priority=priority, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.AcceleratorError: CUDA error: no CUDA-capable device is detected
[rank0]: Search for `cudaErrorNoDevice' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Device-side assertions were explicitly omitted for this error check; the error probably arose while initializing the DSA handlers.
```

**Comment by yaoyu-33** [comment]
@LucaTedeschini : Wonder if you can help us to understand the issue a bit more.
If you think there are few configs are suspicious, can you help to edit checkpoint/iter_**/run_config.yaml file to for example turn off recomputation. The model is initialized with run_config.yaml https://github.com/NVIDIA-NeMo/Megatron-Bridge/blob/9a0f0fe8f1c2e665027396d8b98653156b4690cd/src/megatron/bridge/training/model_load_save.py#L366 . Try to understand if some configs caused the failure in exporting.

**Comment by LucaTedeschini** [comment]
Thanks for the answer. I fixed the problem by looking at recent commits on github: these lines (added 5 days ago) fixed the issue

https://github.com/NVIDIA-NeMo/Megatron-Bridge/blob/5ccbfdfc0adeab6f5e34a5984b6852322ba80fd4/src/megatron/bridge/training/model_load_save.py#L380-L382

I added them locally and now the model does not get loaded into GPU

**Comment by pruprakash** [comment]
## QA RCCA Analysis

### 1. Fix Reference
- **Issue**: #1855 - [BUG] Infinite CUDA OOM during HF export with Activation Recomputation enabled (DeepSeekV3 / MoE)
- **Fix**: Already present in `model_load_save.py` per user comment

### 2. Root Cause
When exporting a Megatron checkpoint trained with Activation Recomputation enabled, the HuggingFace export entered an infinite CUDA OOM loop during tensor merging.

**User found fix**: Lines added 5 days before issue was filed in `model_load_save.py` fixed the issue.

### 3. Trigger Configuration
- DeepSeekV3 / MoE model training
- Activation recomputation enabled (`recompute_granularity=full`)
- Attempt HF export

### 4. Nature of the Bug
**Classification**: CODE BUG - Fixed prior to issue filing

### 5. Existing Test Coverage
The fix was already in the codebase when the issue was filed. User confirmed the issue was resolved by using recent code.

### 6. Coverage Assessment
| Test Type | Exists | Covers Bug |
|-----------|--------|------------|
| Fix already applied | YES | YES |

### 7. New Regression Test
**Deferred** - Would require full MoE model export test with recomputation enabled. The fix was applied proactively.

### 8. Conclusion
**Verdict**: ALREADY FIXED

User confirmed fix was already present in codebase when issue was filed. No additional RCCA needed.
